export const AT_SKILLS = {
    DELETE_SKILL: "DELETE_SKILL",
    CREATE_SKILL: "CREATE_SKILL",
    READ_ALL_SKILL: "READ_ALL_SKILL"
};

export const AT_PROJECTS = {
    DELETE_PROJECT: "DELETE_PROJECT",
    CREATE_PROJECT: "CREATE_PROJECT",
    READ_ALL_PROJECT: "READ_ALL_PROJECT"
};

export const AT_AUTH = {
    SET_AUTHENTICATION: "SET_AUTHENTICATION",
    SET_ERROR: "SET_ERROR"
};